Repository GU-99/grow-up-fe, pull requests merged in 2024-07, with the labels that each got.

#36 Feat: #33 특정 프로젝트 칸반 보드 UI 작성 & 할일 목록 DnD 기능 추가
  .eslintrc.cjs
  package.json
  src/globals.css
  src/layouts/page/ProjectLayout.tsx
  src/mocks/mockData.ts
  src/pages/project/KanbanPage.tsx
  src/types/TodoStatusType.tsx
  src/types/TodoType.tsx
  src/utils/deepClone.ts
  yarn.lock
Labels: ⚙️ Conf, 🌟 Feature, 🎨 UI

#38 Refactor: #33 DnD 순서 변경 함수 통합 & 가독성을 위한 조건문 변수화
  src/pages/project/KanbanPage.tsx
Labels: 🛠️ Refactor

#39 Formatting: #33 기존에 사용하던 Todo라는 이름을 ERD 할일 테이블 이름인 Task으로 통합 (todo → task)
  src/components/modal/ModalTaskStatus.tsx
  src/globals.css
  src/layouts/page/ProjectLayout.tsx
  src/mocks/mockData.ts
  src/pages/project/KanbanPage.tsx
  src/types/TaskStatusType.tsx
  src/types/TaskType.tsx
  tailwind.config.js
Labels: ✨ Formatting

#40 Feat: #33 특정 프로젝트 상태 목록 수평 DnD 기능 추가
  src/pages/project/KanbanPage.tsx
Labels: 🌟 Feature

#41 Refactor: #33 컴포넌트 분리 / types, constants 등 관심사 분리
  src/components/task/kanban/TaskItem.tsx
  src/components/task/kanban/TaskItemList.tsx
  src/components/task/kanban/TaskStatusContainer.tsx
  src/constants/dnd.ts
  src/pages/project/KanbanPage.tsx
  src/types/TaskStatusType.tsx
  src/utils/Validator.ts
  src/utils/converter.ts
Labels: 🛠️ Refactor, ✨ Formatting

#42 Rename: #33 ERD 프로젝트 상태 테이블 이름으로 통합 (TaskStatus → ProjectStatus)
  src/components/modal/ModalProjectStatus.tsx
  src/components/task/kanban/ProjectStatusContainer.tsx
  src/layouts/page/ProjectLayout.tsx
  src/mocks/mockData.ts
  src/pages/project/KanbanPage.tsx
  src/types/ProjectStatusType.tsx
  src/types/TaskType.tsx
Labels: ✨ Formatting

#37 Feat: #5 회원가입 페이지 생성 및 Validation 작성
  .eslintrc.cjs
  package.json
  src/assets/auth_logo.svg
  src/assets/social_google_icon.svg
  src/assets/social_kakao_icon.svg
  src/components/common/ValidationInput.tsx
  src/constants/formValidationRules.ts
  src/constants/regex.ts
  src/globals.css
  src/layouts/page/AuthLayout.tsx
  src/pages/user/SignInPage.tsx
  src/pages/user/SignUpPage.tsx
  src/routes/MainRouter.tsx
  src/types/UserType.tsx
  tailwind.config.js
  yarn.lock
Labels: 🌟 Feature, 🎨 UI

#43 Feat: #27 로그인 페이지 생성 및 Validation 작성
  src/constants/formValidationRules.ts
  src/globals.css
  src/layouts/page/AuthLayout.tsx
  src/pages/user/SignInPage.tsx
  tailwind.config.js
Labels: 🌟 Feature, 🎨 UI

#50 Fix: #49 로그인 페이지 import 오류 수정
  src/pages/user/SignInPage.tsx
Labels: 🐞 Bug, 💉 Fix

#53 Feat: #52 알림을 위한 토스트 메시지 추가
  package.json
  src/hooks/useToast.tsx
  src/layouts/ToastLayout.tsx
  src/routes/MainRouter.tsx
  yarn.lock
Labels: ⚙️ Conf, 🌟 Feature, 🎨 UI

#56 UI: #55 스크롤바 UI 변경
  src/globals.css
Labels: 🎨 UI

#54 Feat: #51 특정 프로젝트 관리 페이지: 캘린더 UI 작성
  package.json
  src/components/sidebar/ListProject.tsx
  src/components/task/calendar/CalendarToolbar.tsx
  src/components/task/calendar/CustomDateHeader.tsx
  src/components/task/calendar/CustomEventWrapper.tsx
  src/components/task/kanban/ProjectStatusContainer.tsx
  src/constants/date.ts
  src/layouts/ModalLayout.tsx
  src/layouts/page/ProjectLayout.tsx
  src/mocks/mockData.ts
  src/pages/project/CalendarPage.tsx
  src/pages/project/KanbanPage.tsx
  src/types/CustomEventType.tsx
  src/types/ProjectType.tsx
  src/types/TaskType.tsx
  yarn.lock
Labels: 🗃️ Chore, ⚙️ Conf, 🌟 Feature, 🎨 UI

#59 UI: #57 프로젝트 레이아웃 UI 변경
  src/components/modal/task/CreateModalTask.tsx
  src/components/modal/task/ModalTaskForm.tsx
  src/components/modal/task/UpdateModalTask.tsx
  src/layouts/page/ProjectLayout.tsx
  src/pages/project/CalendarPage.tsx
  src/types/TaskType.tsx
Labels: 🎨 UI
