Repository GU-99/grow-up-fe, pull requests merged in 2024-08, with the labels that each got.

#60 Feat: #51 특정 프로젝트 관리 페이지: 프로젝트 기간 설정 유무에 따른 날짜 스타일 처리
  src/components/task/calendar/CustomDateHeader.tsx
  src/components/task/kanban/ProjectStatusContainer.tsx
  src/customReactBigCalendar.css
  src/hooks/useProjectContext.tsx
  src/layouts/page/ProjectLayout.tsx
  src/mocks/mockData.ts
  src/pages/project/CalendarPage.tsx
  src/types/CustomEventType.tsx
  src/utils/Validator.ts
Labels: 🗃️ Chore, 🌟 Feature, 🎨 UI

#67 Feat: 할일 등록 모달 토대 UI 작성 & 일정명, 날짜 설정 기능 추가
  .vscode/extensions.json
  src/assets/calendar.svg
  src/components/common/DuplicationCheckInput.tsx
  src/components/common/ToggleButton.tsx
  src/components/modal/ModalFormButton.tsx
  src/components/modal/project-status/CreateModalProjectStatus.tsx
  src/components/modal/project-status/ModalProjectStatusForm.tsx
  src/components/modal/project-status/UpdateModalProjectStatus.tsx
  src/components/modal/task/CreateModalTask.tsx
  src/components/modal/task/ModalTaskForm.tsx
  src/components/modal/task/UpdateModalTask.tsx
  src/constants/formValidationRules.ts
  src/globals.css
  src/hooks/query/useTaskQuery.ts
  src/layouts/ModalLayout.tsx
  src/layouts/page/ProjectLayout.tsx
  src/pages/project/CalendarPage.tsx
  src/types/TaskType.tsx
  src/utils/Validator.ts
Labels: 🖼 Asset, 🌟 Feature, 🎨 UI

#64 UI: #62 모든 프로젝트 관리 페이지 중 팀/프로젝트가 없는 경우 UI 작성
  src/components/modal/team/CreateModalTeam.tsx
  src/components/modal/team/ModalTeamForm.tsx
  src/components/sidebar/ListSidebar.tsx
  src/components/sidebar/ListTeam.tsx
  src/layouts/page/TeamLayout.tsx
  src/mocks/mockData.ts
  src/types/TeamType.tsx
Labels: 🌟 Feature, 🎨 UI

#70 Feat: #63 할일 등록 모달 상태 설정 기능 추가
  src/components/common/ToggleButton.tsx
  src/components/modal/project-status/CreateModalProjectStatus.tsx
  src/components/modal/project-status/ModalProjectStatusForm.tsx
  src/components/modal/project-status/UpdateModalProjectStatus.tsx
  src/components/modal/task/CreateModalTask.tsx
  src/components/modal/task/ModalTaskForm.tsx
  src/components/modal/task/UpdateModalTask.tsx
  src/components/task/kanban/ProjectStatusContainer.tsx
  src/constants/formValidationRules.ts
  src/hooks/query/useProjectStatusQuery.ts
  src/hooks/query/useStatusQuery.ts
  src/layouts/page/ProjectLayout.tsx
  src/types/TaskType.tsx
Labels: 🌟 Feature, ✨ Formatting, 🎨 UI

#66 Feat: #65 회원가입 폼 UI 수정 및 관련 로직 수정
  src/components/common/Timer.tsx
  src/constants/formValidationRules.ts
  src/constants/regex.ts
  src/constants/units.ts
  src/constants/userSettings.ts
  src/pages/user/SearchIdPage.tsx
  src/pages/user/SearchPasswordPage.tsx
  src/pages/user/SignInPage.tsx
  src/pages/user/SignUpPage.tsx
  src/types/UserType.tsx
  src/utils/converter.ts
  src/utils/reduceImageSize.ts
Labels: 🎨 UI

#71 UI: #62 모든 프로젝트 관리 페이지 중 팀/프로젝트가 있는 경우 UI 작성
  src/components/modal/project/CreateModalProject.tsx
  src/components/modal/project/ModalProjectForm.tsx
  src/components/modal/project/UpdateModalProject.tsx
  src/components/modal/team/UpdateModalTeam.tsx
  src/components/sidebar/ListTeam.tsx
  src/layouts/page/TeamLayout.tsx
  src/pages/team/TeamPage.tsx
Labels: 🌟 Feature, 🎨 UI

#73 UI: #69 유저 정보 설정 페이지 UI 구현
  package-lock.json
  src/components/sidebar/ListSetting.tsx
  src/constants/formValidationRules.ts
  src/layouts/page/SettingLayout.tsx
  src/mocks/mockData.ts
  src/pages/setting/UserAuthenticatePage.tsx
  src/pages/setting/UserPasswordSettingPage.tsx
  src/pages/user/SearchIdPage.tsx
  src/pages/user/SearchPasswordPage.tsx
  src/pages/user/SignInPage.tsx
  src/pages/user/SignUpPage.tsx
  src/routes/MainRouter.tsx
  src/types/UserType.tsx
  yarn.lock
Labels: 🌟 Feature, 🎨 UI

#75 Feat: #63 할일 추가 모달 수행자 검색 기능 구현
  src/components/modal/task/ModalTaskForm.tsx
  src/constants/units.ts
  src/hooks/.gitkeep
  src/hooks/useAxios.ts
  src/mocks/browser.ts
  src/mocks/handlers.ts
  src/mocks/mockData.ts
  src/mocks/server.ts
  src/mocks/services/projectServiceHandler.ts
  src/mocks/services/teamServiceHandler.ts
  src/mocks/services/userServiceHandler.ts
  src/services/.gitkeep
  src/services/axiosProvider.ts
  src/services/projectService.ts
  src/services/teamService.ts
  src/services/userService.ts
  src/types/RoleType.tsx
  src/types/UserType.tsx
Labels: 🌟 Feature, ✨ Formatting, 🎨 UI

#77 Config: #76 VSCode 확장앱 추가
  .vscode/extensions.json
Labels: ⚙️ Config

#79 Feat: #63 수행자 목록 UI 추가 & 수행자 추가/삭제 기능 구현
  src/components/modal/task/ModalTaskForm.tsx
  src/layouts/ModalLayout.tsx
  src/layouts/page/ProjectLayout.tsx
  src/mocks/mockData.ts
  src/services/projectService.ts
  src/types/RoleType.tsx
  src/types/TaskType.tsx
  src/types/UserType.tsx
Labels: 🌟 Feature, 🎨 UI

#81 Feat: #63 수행자 권한 표시를 아이콘으로 변경 & 아이콘 툴팁 설명 추가
  src/components/common/RoleIcon.tsx
  src/components/modal/task/ModalTaskForm.tsx
  src/mocks/mockData.ts
Labels: 🌟 Feature, 🎨 UI

#83 Fix: 모든 페이지 관리 팀 모달 props 오류 수정
  src/components/modal/team/ModalTeamForm.tsx
Labels: 💉 Fix

#74 UI: #72 유저 정보 설정 페이지 팀 설정 UI 구현
  src/components/sidebar/ListSidebar.tsx
  src/layouts/page/ProjectLayout.tsx
  src/layouts/page/SettingLayout.tsx
  src/layouts/page/TeamLayout.tsx
  src/mocks/mockData.ts
  src/mocks/services/userServiceHandler.ts
  src/pages/setting/TeamSettingPage.tsx
  src/services/userService.ts
  src/types/TeamType.tsx
Labels: 🎨 UI

#84 Feat: #63 마크다운 기능 추가
  package.json
  src/components/common/CustomMarkdown.tsx
  src/components/modal/task/ModalTaskForm.tsx
  src/mocks/mockData.ts
  src/types/TaskType.tsx
  yarn.lock
Labels: ⚙️ Config, 🌟 Feature, 🎨 UI

#78 UI: #69 유저 정보 설정 페이지 UI 구현
  src/assets/auth_logo.svg
  src/components/common/ValidationInput.tsx
  src/components/user/auth-form/FooterLinks.tsx
  src/components/user/auth-form/LinkContainer.tsx
  src/components/user/auth-form/ProfileImageContainer.tsx
  src/components/user/auth-form/VerificationButton.tsx
  src/globals.css
  src/hooks/useEmailVerification.ts
  src/layouts/AuthFormLayout.tsx
  src/layouts/page/AuthLayout.tsx
  src/layouts/page/SettingLayout.tsx
  src/pages/setting/UserAuthenticatePage.tsx
  src/pages/setting/UserSettingPage.tsx
  src/pages/user/SearchIdPage.tsx
  src/pages/user/SearchPasswordPage.tsx
  src/pages/user/SignInPage.tsx
  src/pages/user/SignUpPage.tsx
  src/types/UserType.tsx
Labels: 🌟 Feature, 🎨 UI

#86 Feat: #63 마크다운 코드 블록 하이라이팅 기능 추가
  .eslintrc.cjs
  package.json
  src/components/common/CustomMarkdown.tsx
  src/constants/language.ts
  yarn.lock
Labels: ⚙️ Config, 🌟 Feature, 🎨 UI

#88 Feat: #63 할일 등록 모달 DnD 파일 첨부 기능 추가
  .eslintrc.cjs
  src/components/modal/task/ModalTaskForm.tsx
  src/components/user/auth-form/LinkContainer.tsx
  src/components/user/auth-form/ProfileImageContainer.tsx
  src/constants/formValidationRules.ts
  src/constants/regex.ts
  src/constants/settings.ts
  src/utils/reduceImageSize.ts
Labels: ⚙️ Config, 🌟 Feature, ✨ Formatting, 🎨 UI

#93 Feat: React Query 기본 환경 설정 & 상태별 프로젝트 일정 전체 조회 API 처리 추가
  package.json
  src/components/modal/task/ModalTaskForm.tsx
  src/hooks/errorHandler.ts
  src/hooks/query/queryClient.ts
  src/hooks/query/useTaskQuery.ts
  src/hooks/useAxios.ts
  src/main.tsx
  src/mocks/handlers.ts
  src/mocks/mockData.ts
  src/mocks/services/taskServiceHandler.ts
  src/pages/project/CalendarPage.tsx
  src/pages/project/KanbanPage.tsx
  src/services/taskService.ts
  src/types/ProjectStatusType.tsx
  src/types/TaskType.tsx
  yarn.lock
Labels: 🗃️ Chore, ⚙️ Config, 🌟 Feature

#95 Chore: #94 프로젝트 상태, 프로젝트, 할일 타입 재정의
  src/components/modal/project-status/ModalProjectStatusForm.tsx
  src/components/modal/project/ModalProjectForm.tsx
  src/components/modal/task/ModalTaskForm.tsx
  src/components/modal/team/ModalTeamForm.tsx
  src/components/task/calendar/CustomEventWrapper.tsx
  src/components/task/kanban/ProjectStatusContainer.tsx
  src/components/task/kanban/TaskItem.tsx
  src/components/task/kanban/TaskItemList.tsx
  src/hooks/query/useStatusQuery.ts
  src/mocks/mockData.ts
  src/pages/project/CalendarPage.tsx
  src/pages/project/KanbanPage.tsx
  src/types/ProjectStatusType.tsx
  src/types/ProjectType.tsx
  src/types/TaskType.tsx
Labels: 🗃️ Chore

#96 Fix: #90 마크다운 코드 블록 내 개행문자가 <br />로 치환되는 문제 해결
  src/components/common/CustomMarkdown.tsx
Labels: 💉 Fix
