Repository GU-99/grow-up-fe, pull requests merged in 2024-09, with the labels that each got.

#99 Feat: #98 프로젝트 상태 목록 조회 API 기능 구현
  src/components/common/Spinner.tsx
  src/components/modal/project-status/ModalProjectStatusForm.tsx
  src/components/modal/task/ModalTaskForm.tsx
  src/hooks/query/useStatusQuery.ts
  src/mocks/handlers.ts
  src/mocks/services/statusServiceHandler.ts
  src/services/statusService.ts
Labels: 🌟 Feature, 🎨 UI

#103 Feat: #101 프로젝트 상태 생성 API를 이용하여 상태 생성 기능 구현
  src/components/modal/project-status/CreateModalProjectStatus.tsx
  src/components/modal/project-status/ModalProjectStatusForm.tsx
  src/components/modal/task/ModalTaskForm.tsx
  src/components/task/kanban/ProjectStatusContainer.tsx
  src/hooks/query/useStatusQuery.ts
  src/mocks/mockData.ts
  src/mocks/services/statusServiceHandler.ts
  src/pages/project/CalendarPage.tsx
  src/services/statusService.ts
  src/types/ProjectStatusType.tsx
  src/types/TaskType.tsx
Labels: 🌟 Feature

#106 Feat: #102 프로젝트 상태 변경 API를 이용하여 상태 변경 기능 구현
  src/components/modal/project-status/UpdateModalProjectStatus.tsx
  src/hooks/query/useStatusQuery.ts
  src/mocks/services/statusServiceHandler.ts
  src/services/statusService.ts
Labels: 🌟 Feature

#108 UI: #107 모달 레이아웃 UI 수정
  src/components/modal/ModalFormButton.tsx
  src/components/modal/project-status/ModalProjectStatusForm.tsx
  src/layouts/ModalLayout.tsx
Labels: 🎨 UI

#110 Feat: #109 프로젝트 목록 조회 기능 구현
  src/components/common/Spinner.tsx
  src/components/modal/project-status/ModalProjectStatusForm.tsx
  src/components/modal/task/ModalTaskForm.tsx
  src/hooks/query/useProjectQuery.ts
  src/layouts/page/ProjectLayout.tsx
  src/mocks/services/projectServiceHandler.ts
  src/services/projectService.ts
Labels: 🌟 Feature

#100 Feat: #80 로컬 로그인 기능 구현
  src/components/user/auth-form/ProfileImageContainer.tsx
  src/constants/settings.ts
  src/hooks/useAxios.ts
  src/mocks/handlers.ts
  src/mocks/mockData.ts
  src/mocks/services/authServiceHandler.ts
  src/pages/setting/UserSettingPage.tsx
  src/pages/user/SearchPasswordPage.tsx
  src/pages/user/SignInPage.tsx
  src/pages/user/SignUpPage.tsx
  src/services/authService.ts
  src/services/axiosProvider.ts
  src/stores/useAuthStore.ts
  src/types/UserType.tsx
  yarn.lock
Labels: 🌟 Feature, 🆘 Help

#112 Feat: #104 일정 순서 변경 API를 이용하여 칸반 보드 DnD로 일정의 순서를 변경하는 기능 구현
  src/components/modal/task/ModalTaskForm.tsx
  src/hooks/query/useStatusQuery.ts
  src/hooks/query/useTaskQuery.ts
  src/mocks/mockHash.ts
  src/mocks/services/taskServiceHandler.ts
  src/pages/project/CalendarPage.tsx
  src/pages/project/KanbanPage.tsx
  src/services/taskService.ts
  src/types/TaskType.tsx
Labels: 🌟 Feature, ✨ Formatting

#113 Feat: #105 상태 순서 변경 API를 이용하여 칸반 보드 DnD로 상태의 순서를 변경하는 기능 구현
  src/hooks/query/useStatusQuery.ts
  src/mocks/services/statusServiceHandler.ts
  src/pages/project/KanbanPage.tsx
  src/services/projectService.ts
  src/services/statusService.ts
  src/services/taskService.ts
  src/services/teamService.ts
  src/types/ProjectStatusType.tsx
Labels: 🗃️ Chore, 🌟 Feature

#97 UI: #85 모든 프로젝트 및 팀 설정 페이지 UI 변경
  src/components/sidebar/ListTeam.tsx
  src/hooks/query/useTeamQuery.ts
  src/layouts/page/SettingLayout.tsx
  src/layouts/page/TeamSettingLayout.tsx
  src/mocks/mockData.ts
  src/mocks/services/userServiceHandler.ts
  src/pages/setting/TeamInvitedPage.tsx
  src/pages/setting/TeamJoinedPage.tsx
  src/pages/setting/TeamSettingPage.tsx
  src/pages/team/TeamPage.tsx
  src/routes/MainRouter.tsx
  src/services/userService.ts
  src/types/TeamType.tsx
Labels: 🎨 UI

#119 Fix: #117 상태 추가 후 상태 순서 변경시 발생하는 에러 해결
  src/hooks/query/useStatusQuery.ts
  src/mocks/mockHash.ts
  src/mocks/services/statusServiceHandler.ts
  src/mocks/services/taskServiceHandler.ts
Labels: 💉 Fix

#116 Feat: #111 액세스 토큰 갱신 기능 구현
  package.json
  src/constants/settings.ts
  src/mocks/services/authServiceHandler.ts
  src/services/authService.ts
  src/services/axiosProvider.ts
  yarn.lock
Labels: 🌟 Feature

#124 Fix: #122 칸반 보드 UI가 정해진 범위를 넘어가는 문제 해결
  src/components/sidebar/ListSidebar.tsx
  src/components/task/kanban/TaskItem.tsx
  src/components/task/kanban/TaskItemList.tsx
  src/layouts/page/ProjectLayout.tsx
  src/layouts/page/SettingLayout.tsx
  src/layouts/page/TeamLayout.tsx
  src/mocks/services/taskServiceHandler.ts
  src/pages/project/CalendarPage.tsx
  src/pages/project/KanbanPage.tsx
Labels: 💉 Fix

#125 Feat: #114 일정 생성 API를 이용하여 일정 생성 기능 구현
  src/components/modal/task/CreateModalTask.tsx
  src/components/modal/task/ModalTaskForm.tsx
  src/hooks/query/useTaskQuery.ts
  src/mocks/services/taskServiceHandler.ts
  src/services/taskService.ts
Labels: 🌟 Feature

#121 Feat: #118 로그인 후 유저 정보 호출 기능 구현
  package.json
  src/components/common/Header.tsx
  src/components/user/auth-form/ProfileImageContainer.tsx
  src/mocks/mockData.ts
  src/mocks/services/authServiceHandler.ts
  src/pages/setting/UserSettingPage.tsx
  src/pages/user/SignInPage.tsx
  src/pages/user/SignUpPage.tsx
  src/services/authService.ts
  src/services/axiosProvider.ts
  src/stores/useAuthStore.ts
  src/stores/useStore.ts
  src/types/UserType.tsx
  src/utils/cryptoHelper.ts
  tsconfig.json
  vite.config.ts
  yarn.lock
Labels: 🌟 Feature

#129 Chore: #128 유저 정보 값 수정
  src/components/user/auth-form/ProfileImageContainer.tsx
  src/mocks/mockData.ts
  src/pages/setting/UserSettingPage.tsx
  src/pages/user/SignUpPage.tsx
  src/services/authService.ts
  src/stores/useStore.ts
  src/types/UserType.tsx
Labels: 🗃️ Chore

#130 UI: #89 일정 상세보기 모달 UI 작성
  src/components/common/CustomMarkdown.tsx
  src/components/modal/ModalFormButton.tsx
  src/components/task/kanban/TaskItem.tsx
  src/components/task/kanban/TaskItemList.tsx
  src/hooks/query/useStatusQuery.ts
  src/mocks/mockData.ts
  src/pages/project/CalendarPage.tsx
  src/pages/project/KanbanPage.tsx
Labels: 🎨 UI

#131 UI: #127 일정 등록 입력 양식들을 컴포넌트로 분리
  src/components/common/FileDropZone.tsx
  src/components/common/MarkdownEditor.tsx
  src/components/common/PeriodDateInput.tsx
  src/components/common/StatusRadio.tsx
  src/components/modal/task/ModalTaskForm.tsx
  src/types/FileType.tsx
Labels: 🎨 UI

#136 Feat: #134 일정 수행자 조회 기능 추가
  src/components/modal/task/DetailModalTask.tsx
  src/components/modal/task/ModalTaskForm.tsx
  src/hooks/query/useTaskQuery.ts
  src/mocks/mockData.ts
  src/mocks/services/taskServiceHandler.ts
  src/services/taskService.ts
  src/types/AssigneeType.tsx
  src/types/TaskType.tsx
Labels: 🌟 Feature

#133 Feat: #123 로그아웃 기능 구현
  src/components/common/Header.tsx
  src/mocks/services/authServiceHandler.ts
  src/pages/user/SignInPage.tsx
  src/routes/MainRouter.tsx
  src/services/authService.ts
  src/services/axiosProvider.ts
  src/stores/useStore.ts
Labels: 🌟 Feature

#138 Feat: #135 일정 파일 목록 조회 기능 추가
  src/components/modal/task/DetailModalTask.tsx
  src/hooks/query/useTaskQuery.ts
  src/mocks/mockData.ts
  src/mocks/services/taskServiceHandler.ts
  src/services/taskService.ts
  src/types/FileType.tsx
  src/types/TaskType.tsx
Labels: 🌟 Feature

#141 Feat: #140 마크다운 커스텀 a태그 속성 수정
  src/components/common/CustomMarkdown.tsx
Labels: 🌟 Feature

#126 Feat: #120 팀 설정 페이지 탈퇴 삭제 및 수락 거부 기능 구현
  src/hooks/query/useTeamQuery.ts
  src/mocks/services/teamServiceHandler.ts
  src/mocks/services/userServiceHandler.ts
  src/pages/setting/TeamInvitedPage.tsx
  src/pages/setting/TeamJoinedPage.tsx
  src/services/teamService.ts
  src/types/TeamType.tsx
Labels: 🌟 Feature

#139 Feat: #137 아이디/비밀번호 찾기 기능 구현
  src/components/user/auth-form/FooterLinks.tsx
  src/components/user/auth-form/SearchDataForm.tsx
  src/components/user/auth-form/SearchResultSection.tsx
  src/hooks/useEmailVerification.ts
  src/layouts/AuthFormLayout.tsx
  src/layouts/page/AuthLayout.tsx
  src/mocks/services/authServiceHandler.ts
  src/pages/user/SearchIdPage.tsx
  src/pages/user/SearchPasswordPage.tsx
  src/pages/user/SignInPage.tsx
  src/services/authService.ts
  src/services/axiosProvider.ts
  src/types/UserType.tsx
  src/utils/converter.ts
Labels: 🌟 Feature, 🎨 UI

#145 Feat: #144 비밀번호 변경 기능 구현
  src/constants/formValidationRules.ts
  src/mocks/mockData.ts
  src/mocks/services/authServiceHandler.ts
  src/pages/setting/UserPasswordSettingPage.tsx
  src/services/authService.ts
  src/types/UserType.tsx
Labels: 🌟 Feature

#143 Feat: #142 이메일 인증 기능 구현
  src/components/user/auth-form/FooterLinks.tsx
  src/components/user/auth-form/SearchDataForm.tsx
  src/components/user/auth-form/SearchResultSection.tsx
  src/hooks/useEmailVerification.ts
  src/mocks/mockData.ts
  src/mocks/services/authServiceHandler.ts
  src/pages/setting/UserAuthenticatePage.tsx
  src/pages/user/SearchIdPage.tsx
  src/pages/user/SearchPasswordPage.tsx
  src/pages/user/SignUpPage.tsx
  src/services/authService.ts
  src/types/UserType.tsx
Labels: 🌟 Feature

#151 UI: 파일 드래그 앤 드롭시 영역 스타일 가시성 스타일 추가
  src/components/common/FileDropZone.tsx
  src/components/modal/task/ModalTaskForm.tsx
  src/components/modal/task/UpdateModalTask.tsx
  src/hooks/query/useTaskQuery.ts
  src/mocks/services/taskServiceHandler.ts
  src/services/taskService.ts
  src/types/TaskType.tsx
Labels: 🎨 UI

#152 Feat: #147 수행자 검색 API 변경으로 인한 수행자 검색 기능 수정
  src/components/common/AssigneeList.tsx
  src/components/common/SearchUserInput.tsx
  src/components/modal/task/ModalTaskForm.tsx
  src/hooks/query/useProjectQuery.ts
  src/hooks/useProjectContext.tsx
  src/layouts/page/ProjectLayout.tsx
  src/mocks/services/projectServiceHandler.ts
  src/services/projectService.ts
  src/types/UserType.tsx
Labels: 🌟 Feature

#154 Refactor: #153 유저 검색을 위한 SearchUserInput 컴포넌트 리팩토링
  src/components/common/SearchUserInput.tsx
  src/components/modal/task/ModalTaskForm.tsx
  src/services/teamService.ts
  src/services/userService.ts
  src/types/SearchCallbackType.tsx
  src/utils/exhaustiveCheck.ts
Labels: 🛠️ Refactor

#155 Feat: 일정 수정 모달 UI 변경 사항 반영
  src/components/common/FileDropZone.tsx
  src/components/modal/ModalFormButton.tsx
  src/components/modal/task/ModalTaskForm.tsx
  src/components/modal/task/UpdateModalTask.tsx
  src/hooks/query/useTaskQuery.ts
  src/mocks/mockData.ts
  src/mocks/services/taskServiceHandler.ts
  src/services/taskService.ts
  src/types/AssigneeType.tsx
  src/types/FileType.tsx
  src/types/TaskType.tsx
Labels: 🌟 Feature, 🛠️ Refactor, 🎨 UI

#157 Feat: #149 일정 수정 모달 수행자 추가 기능 구현
  src/components/modal/task/UpdateModalTask.tsx
  src/hooks/query/useTaskQuery.ts
  src/mocks/services/taskServiceHandler.ts
  src/services/taskService.ts
  src/types/TaskType.tsx
Labels: 🌟 Feature

#158 Feat: #150 일정 수정 모달 수행자 삭제 기능 구현
  src/components/modal/task/UpdateModalTask.tsx
  src/hooks/query/useTaskQuery.ts
  src/mocks/services/taskServiceHandler.ts
  src/services/taskService.ts
Labels: 🌟 Feature

#160 Feat: #156 일정 수정 모달 일정 정보 변경 기능 구현
  src/components/modal/task/UpdateModalTask.tsx
  src/hooks/query/useTaskQuery.ts
  src/mocks/services/taskServiceHandler.ts
  src/services/taskService.ts
Labels: 🌟 Feature

#164 Fix: #163 일정 수정 모달에서 상태 선택 정보가 사라지는 문제 해결
  src/components/common/StatusRadio.tsx
  src/components/modal/task/UpdateModalTask.tsx
  src/hooks/query/useTaskQuery.ts
  src/mocks/services/taskServiceHandler.ts
  src/services/taskService.ts
  src/types/TaskType.tsx
Labels: 💉 Fix

#162 Feat: #146 비밀번호 변경 전 인증 페이지의 인증 로직 구현
  src/components/user/auth-form/SearchDataForm.tsx
  src/constants/formValidationRules.ts
  src/constants/settings.ts
  src/mocks/mockData.ts
  src/mocks/services/authServiceHandler.ts
  src/pages/setting/UserAuthenticatePage.tsx
  src/pages/setting/UserPasswordSettingPage.tsx
  src/pages/setting/UserSettingPage.tsx
  src/pages/user/SearchIdPage.tsx
  src/pages/user/SearchPasswordPage.tsx
  src/pages/user/SignUpPage.tsx
  src/services/authService.ts
  src/services/axiosProvider.ts
  src/stores/useStore.ts
  src/types/UserType.tsx
Labels: 🌟 Feature

#166 Feat: #115 일정 등록 모달의 파일 업로드 기능 구현
  src/components/common/FileDropZone.tsx
  src/components/modal/task/CreateModalTask.tsx
  src/components/modal/task/ModalTaskForm.tsx
  src/components/modal/task/UpdateModalTask.tsx
  src/constants/mimeFileType.ts
  src/constants/regex.ts
  src/constants/settings.ts
  src/hooks/query/useTaskQuery.ts
  src/mocks/mockData.ts
  src/mocks/mockHash.ts
  src/mocks/services/taskServiceHandler.ts
  src/services/taskService.ts
  src/types/FileType.tsx
  src/types/TaskType.tsx
  src/utils/Validator.ts
Labels: 🗃️ Chore, 🌟 Feature, 🎨 UI

#174 Refactor: #173 React Query의 Query Key 정리
  src/hooks/query/useProjectQuery.ts
  src/hooks/query/useStatusQuery.ts
  src/hooks/query/useTaskQuery.ts
  src/hooks/query/useTeamQuery.ts
  src/utils/queryKeyGenergator.ts
Labels: 🛠️ Refactor

#176 Feat: #167 일정 수정 모달의 일정 파일 삭제 기능 구현
  src/components/common/FileDropZone.tsx
  src/components/modal/task/UpdateModalTask.tsx
  src/hooks/query/useTaskQuery.ts
  src/mocks/services/taskServiceHandler.ts
  src/services/taskService.ts
Labels: 🌟 Feature

#179 UI: #178 ModalFormButton 제거 및 ModalButton으로 대체
  src/components/modal/ModalButton.tsx
  src/components/modal/ModalFormButton.tsx
  src/components/modal/project-status/CreateModalProjectStatus.tsx
  src/components/modal/project-status/UpdateModalProjectStatus.tsx
  src/components/modal/project/CreateModalProject.tsx
  src/components/modal/project/UpdateModalProject.tsx
  src/components/modal/task/CreateModalTask.tsx
  src/components/modal/task/UpdateModalTask.tsx
  src/components/modal/team/CreateModalTeam.tsx
  src/components/modal/team/UpdateModalTeam.tsx
Labels: 🎨 UI
