Repository GU-99/grow-up-fe, pull requests merged in 2024-10, with the labels that each got.

#180 Feat: #169 상태 삭제 기능 구현
  src/components/modal/project-status/UpdateModalProjectStatus.tsx
  src/hooks/query/queryClient.ts
  src/hooks/query/useStatusQuery.ts
  src/hooks/query/useTaskQuery.ts
  src/mocks/services/statusServiceHandler.ts
  src/services/statusService.ts
Labels: 🌟 Feature

#161 Feat: #87 팀 생성 UI 및 로직 추가
  src/components/common/DescriptionTextarea.tsx
  src/components/common/RoleTooltip.tsx
  src/components/common/SearchUserInput.tsx
  src/components/common/UserRoleSelectBox.tsx
  src/components/modal/team/CreateModalTeam.tsx
  src/components/modal/team/ModalTeamForm.tsx
  src/components/modal/team/UpdateModalTeam.tsx
  src/constants/formValidationRules.ts
  src/constants/regex.ts
  src/constants/role.ts
  src/hooks/query/useTeamQuery.ts
  src/mocks/services/teamServiceHandler.ts
  src/mocks/services/userServiceHandler.ts
  src/services/teamService.ts
  src/types/RoleType.tsx
  src/types/TeamType.tsx
Labels: 🌟 Feature, 🎨 UI

#184 Fix: #182 칸반 보드에서 일정 삭제 / 상태 삭제 후 순서 변경이 제대로 일어나지 않는 문제 해결
  src/mocks/services/statusServiceHandler.ts
  src/mocks/services/taskServiceHandler.ts
Labels: 💉 Fix

#185 Formatting: #183 파일 목록 조회 API의 응답 데이터 구조 변경 반영
  src/components/modal/task/DetailModalTask.tsx
  src/mocks/mockData.ts
  src/mocks/services/taskServiceHandler.ts
  src/types/FileType.tsx
Labels: ✨ Formatting

#181 Feat: #175 유저 프로필 변경 페이지 기능 구현
  src/constants/settings.ts
  src/hooks/query/useUserQuery.ts
  src/hooks/useNicknameDuplicateCheck.ts
  src/mocks/services/userServiceHandler.ts
  src/pages/setting/UserSettingPage.tsx
  src/pages/user/SignUpPage.tsx
  src/services/userService.ts
  src/stores/useStore.ts
  src/types/UserType.tsx
  src/utils/queryKeyGenergator.ts
Labels: 🌟 Feature, 🛠️ Refactor, 🎨 UI

#186 Feat: #168 일정 파일 다운로드 기능 구현
  src/components/modal/task/DetailModalTask.tsx
  src/hooks/useAxios.ts
  src/mocks/mockData.ts
  src/mocks/services/taskServiceHandler.ts
  src/services/taskService.ts
  src/types/SearchCallbackType.tsx
  src/utils/fileNameParser.ts
Labels: 🌟 Feature

#189 Feat: #187 일정 수정 모달 파일 업로드 기능 추가
  src/components/common/FileDropZone.tsx
  src/components/modal/task/CreateModalTask.tsx
  src/components/modal/task/ModalTaskForm.tsx
  src/components/modal/task/UpdateModalTask.tsx
  src/hooks/query/useProjectQuery.ts
  src/hooks/query/useStatusQuery.ts
  src/hooks/query/useTaskQuery.ts
  src/hooks/query/useTeamQuery.ts
  src/hooks/query/useUserQuery.ts
  src/hooks/useTaskFile.ts
  src/utils/queryKeyGenerator.ts
Labels: 🌟 Feature, 🛠️ Refactor

#190 Feat: #188 일정 상세 모달 수정 버튼 기능 구현 (상세 모달 → 수정 모달 전환)
  src/components/modal/task/DetailModalTask.tsx
  src/components/task/kanban/TaskItem.tsx
  src/pages/project/CalendarPage.tsx
  src/pages/project/KanbanPage.tsx
Labels: 🌟 Feature

#191 Feat: #172 소셜 회원가입/로그인 기능 구현
  src/components/user/auth-form/SocialButton.tsx
  src/layouts/AuthFormLayout.tsx
  src/mocks/services/authServiceHandler.ts
  src/pages/user/SignInPage.tsx
  src/pages/user/SocialCallBackPage.tsx
  src/routes/MainRouter.tsx
  src/services/authService.ts
  src/types/UserType.tsx
Labels: 🌟 Feature

#203 Fix: #202 Calendar 컴포넌트 events 타입 호환 문제 해결
  src/pages/project/CalendarPage.tsx
  src/types/TaskType.tsx
Labels: 💉 Fix

#195 Feat: #165 팀 수정 모달 UI 및 기능 구현
  src/components/common/UserRoleSelectBox.tsx
  src/components/modal/team/ModalTeamForm.tsx
  src/components/modal/team/UpdateModalTeam.tsx
  src/hooks/query/useTeamQuery.ts
  src/layouts/page/TeamLayout.tsx
  src/mocks/services/teamServiceHandler.ts
  src/services/teamService.ts
  src/types/TeamType.tsx
  src/utils/queryKeyGenerator.ts
Labels: 🌟 Feature, 🎨 UI

#205 Feat: #204 일정 수정 모달에서 일정 상세 모달로 돌아가기 버튼 추가
  src/components/modal/ModalButton.tsx
  src/components/modal/project-status/CreateModalProjectStatus.tsx
  src/components/modal/project-status/UpdateModalProjectStatus.tsx
  src/components/modal/project/CreateModalProject.tsx
  src/components/modal/project/UpdateModalProject.tsx
  src/components/modal/task/CreateModalTask.tsx
  src/components/modal/task/DetailModalTask.tsx
  src/components/modal/task/UpdateModalTask.tsx
  src/components/modal/team/CreateModalTeam.tsx
  src/components/modal/team/UpdateModalTeam.tsx
  src/components/task/calendar/CustomEventWrapper.tsx
  src/components/task/kanban/TaskItem.tsx
  src/hooks/query/useTaskQuery.ts
  src/pages/project/CalendarPage.tsx
  src/pages/project/KanbanPage.tsx
Labels: 🌟 Feature, 🛠️ Refactor

#209 Feat: #208 PeriodDateInput 컴포넌트 종료일 토글 자동 활성화 기능 추가
  src/components/common/PeriodDateInput.tsx
  src/components/modal/task/ModalTaskForm.tsx
  src/components/modal/task/UpdateModalTask.tsx
  src/services/projectService.ts
  src/utils/Validator.ts
Labels: 🌟 Feature

#215 Fix: #214 프로젝트 목록 및 팀 목록 쿼리로 변경
  src/components/sidebar/ListTeam.tsx
  src/layouts/page/TeamLayout.tsx
  src/pages/team/TeamPage.tsx
Labels: 💉 Fix

#193 Feat: #192 링크 수정 기능 구현
  src/components/user/auth-form/LinkContainer.tsx
  src/hooks/query/useUserQuery.ts
  src/mocks/services/userServiceHandler.ts
  src/pages/setting/UserSettingPage.tsx
  src/pages/user/SignUpPage.tsx
  src/services/userService.ts
  src/stores/useStore.ts
  src/types/UserType.tsx
  src/utils/queryKeyGenerator.ts
Labels: 🌟 Feature

#213 Feat: #210 프로젝트 삭제 기능 추가
  src/components/modal/project-status/CreateModalProjectStatus.tsx
  src/hooks/query/useProjectQuery.ts
  src/layouts/page/TeamLayout.tsx
  src/mocks/services/projectServiceHandler.ts
  src/pages/team/TeamPage.tsx
  src/services/projectService.ts
Labels: 🌟 Feature

#217 Fix: #216 home 페이지로 이동시 teams 페이지로 리다이렉션
  src/routes/MainRouter.tsx
Labels: 💉 Fix

#219 Refactor: #196 MSW중 TaskService 관련 기능 리팩토링
  src/mocks/mockAPI.ts
  src/mocks/mockData.ts
  src/mocks/services/taskServiceHandler.ts
  src/mocks/services/userServiceHandler.ts
  src/types/MockType.tsx
  src/utils/Validator.ts
Labels: 🛠️ Refactor

#218 UI:#199 프로젝트 생성 UI 구현
  src/components/modal/project/CreateModalProject.tsx
  src/components/modal/project/ModalProjectForm.tsx
  src/constants/formValidationRules.ts
  src/constants/role.ts
  src/pages/team/TeamPage.tsx
  src/types/ProjectType.tsx
Labels: 🎨 UI

#223 Fix: #222 인증여부에 따라 헤더의 문구와 로그아웃 버튼 노출하도록 수정
  src/components/common/Header.tsx
  src/mocks/services/authServiceHandler.ts
Labels: 💉 Fix

#226 Refactor: #224 MSW 처리중 StatusService, ProjectService 기능 리팩토링
  src/mocks/mockAPI.ts
  src/mocks/services/projectServiceHandler.ts
  src/mocks/services/statusServiceHandler.ts
  src/mocks/services/taskServiceHandler.ts
Labels: 💉 Fix, 🛠️ Refactor

#212 Feat: #211 유저 프로필 이미지 업로드 기능 구현
  src/components/user/auth-form/ProfileImageContainer.tsx
  src/hooks/query/useUserQuery.ts
  src/mocks/mockData.ts
  src/mocks/services/userServiceHandler.ts
  src/pages/setting/UserSettingPage.tsx
  src/services/userService.ts
  src/stores/useStore.ts
  src/types/UserType.tsx
  src/utils/queryKeyGenerator.ts
Labels: 🌟 Feature, 🆘 Help

#229 Feat: #228 유저 인증을 위한 MSW 수정 및 페이지 라우트 인증 처리
  src/mocks/services/authServiceHandler.ts
  src/mocks/services/userServiceHandler.ts
  src/routes/AfterLoginRoute.tsx
  src/routes/BeforeLoginRoute.tsx
  src/services/axiosProvider.ts
Labels: 🌟 Feature

#237 Chore: #236 axiosProvider에서 JWT 더미데이터 삭제
  src/components/common/Header.tsx
  src/services/axiosProvider.ts
Labels: 🗃️ Chore

#227 Fix:#225 팀 쿼리 키 userId 추가 및 프로젝트 목록 조회 teamId null시 처리 추가
  src/components/modal/project/UpdateModalProject.tsx
  src/hooks/query/useProjectQuery.ts
  src/hooks/query/useTeamQuery.ts
  src/mocks/services/projectServiceHandler.ts
  src/utils/queryKeyGenerator.ts
Labels: 💉 Fix

#240 Feat: #200 프로젝트 생성
  src/components/common/DescriptionTextarea.tsx
  src/components/common/PeriodDateInput.tsx
  src/components/modal/project/CreateModalProject.tsx
  src/components/modal/project/ModalProjectForm.tsx
  src/components/modal/team/ModalTeamForm.tsx
  src/components/modal/team/UpdateModalTeam.tsx
  src/constants/formValidationRules.ts
  src/constants/role.ts
  src/hooks/query/useProjectQuery.ts
  src/hooks/query/useTeamQuery.ts
  src/mocks/mockAPI.ts
  src/mocks/mockData.ts
  src/mocks/services/projectServiceHandler.ts
  src/mocks/services/teamServiceHandler.ts
  src/pages/project/CalendarPage.tsx
  src/pages/team/TeamPage.tsx
  src/services/projectService.ts
  src/types/ProjectType.tsx
  src/utils/Validator.ts
Labels: 🌟 Feature, 🎨 UI

#239 Fix: #238 등록된 프로젝트 상태가 없을 때, 일정 등록을 시도하면 발생하는 문제 해결
  src/components/common/StatusRadio.tsx
  src/components/modal/task/ModalTaskForm.tsx
  src/layouts/page/ProjectLayout.tsx
Labels: 💉 Fix

#244 Refactor: #243 전체 일정 조회에서 단일 일정 조회 로직 분리
  src/components/modal/project-status/UpdateModalProjectStatus.tsx
  src/components/modal/task/DetailModalTask.tsx
  src/components/modal/task/ModalTaskForm.tsx
  src/components/modal/task/UpdateModalTask.tsx
  src/hooks/query/useTaskQuery.ts
  src/utils/extractNameList.ts
Labels: 🛠️ Refactor

#242 UI: #241 프로젝트 수정 UI 구현
  src/components/modal/project/ModalProjectForm.tsx
  src/components/modal/project/UpdateModalProject.tsx
  src/components/modal/task/ModalTaskForm.tsx
  src/components/modal/task/UpdateModalTask.tsx
  src/components/modal/team/ModalTeamForm.tsx
  src/components/modal/team/UpdateModalTeam.tsx
  src/constants/formValidationRules.ts
  src/hooks/query/useProjectQuery.ts
  src/hooks/query/useTeamQuery.ts
  src/hooks/useProjectContext.tsx
  src/layouts/page/ProjectLayout.tsx
  src/utils/extractNameList.ts
Labels: 🎨 UI

#249 Refactor: #248 전체 상태 조회에서 단일 상태 조회 로직 분리
  src/components/modal/project-status/ModalProjectStatusForm.tsx
  src/components/modal/project/ModalProjectForm.tsx
  src/components/modal/project/UpdateModalProject.tsx
  src/components/modal/task/DetailModalTask.tsx
  src/components/modal/task/ModalTaskForm.tsx
  src/components/modal/task/UpdateModalTask.tsx
  src/components/modal/team/ModalTeamForm.tsx
  src/components/modal/team/UpdateModalTeam.tsx
  src/hooks/query/useStatusQuery.ts
  src/hooks/query/useTaskQuery.ts
  src/layouts/page/ProjectLayout.tsx
  src/utils/extractDataList.ts
  src/utils/extractNameList.ts
Labels: 🛠️ Refactor

#250 Feat: #246 프로젝트 수정 기능 구현
  src/components/modal/project/UpdateModalProject.tsx
  src/components/modal/team/UpdateModalTeam.tsx
  src/hooks/query/useProjectQuery.ts
  src/mocks/services/projectServiceHandler.ts
  src/services/projectService.ts
Labels: 🌟 Feature

#247 Fix: #245 accesstoken 더미 데이터를 유저 데이터로 수정
  src/mocks/services/teamServiceHandler.ts
  src/pages/setting/TeamJoinedPage.tsx
Labels: 💉 Fix

#234 Chore: #231 이메일 인증 관련 코드 검토 및 주석 제거
  src/mocks/services/authServiceHandler.ts
  src/pages/setting/UserPasswordSettingPage.tsx
  src/services/authService.ts
  src/services/userService.ts
Labels: 🗃️ Chore, 🌟 Feature

#255 Config: #254 테스트를 위한 환경 설정 추가
  .gitignore
  package.json
  src/components/modal/project/ModalProjectForm.tsx
  src/components/modal/project/UpdateModalProject.tsx
  src/components/modal/team/UpdateModalTeam.tsx
  src/mocks/services/authServiceHandler.ts
  src/mocks/services/teamServiceHandler.ts
  src/pages/project/CalendarPage.tsx
  src/services/axiosProvider.ts
  tsconfig.prod.json
  yarn.lock
Labels: ⚙️ Config
