Repository GU-99/grow-up-fe, pull requests merged in 2024-12, with the labels that each got.

#272 Feat: #230 유저 프로필 이미지 삭제 기능 구현
  src/components/user/auth-form/ProfileImageContainer.tsx
  src/hooks/query/useUserQuery.ts
  src/mocks/services/userServiceHandler.ts
  src/services/userService.ts
Labels: 🌟 Feature

#268 Feat: #265 프로젝트 생성 및 수정 권한 설정 추가
  src/components/modal/team/UpdateModalTeam.tsx
  src/components/project/EmptyProjectItemList.tsx
  src/components/project/ProjectItem.tsx
  src/components/project/ProjectItemList.tsx
  src/hooks/query/useTeamQuery.ts
  src/layouts/page/TeamLayout.tsx
  src/pages/team/TeamPage.tsx
Labels: 🌟 Feature

#286 Config: #285 소셜 로그인 리다이렉트 URL 설정 & checkout 브랜치 명시
  .github/workflows/deploy.yaml
Labels: ⚙️ Config

#289 Fix: #288 Github Actions AWS 배포 스크립트 환경변수명 수정
  .github/workflows/deploy.yaml
Labels: 💉 Fix

#293 Config: #292 develop 브랜치에서 배포할 수 있도록 임시 허용
  .github/workflows/deploy.yaml
Labels: ⚙️ Config

#294 Fix: #291 소셜로그인 callback URL 오류 수정
  src/components/user/auth-form/SocialButton.tsx
  src/mocks/mockData.ts
  src/mocks/services/authServiceHandler.ts
  src/pages/user/SignInPage.tsx
  src/routes/MainRouter.tsx
  src/types/UserType.tsx
Labels: 🐞 Bug, 💉 Fix, ✨ Formatting

#284 Fix: #279 이미지 업로드 및 조회 오류 수정
  src/components/user/auth-form/ProfileImageContainer.tsx
  src/hooks/query/useUserQuery.ts
  src/mocks/mockData.ts
  src/mocks/services/authServiceHandler.ts
  src/mocks/services/userServiceHandler.ts
  src/pages/setting/UserSettingPage.tsx
  src/stores/useStore.ts
  src/types/UserType.tsx
Labels: 💉 Fix, ✨ Formatting

#287 Fix: #282 검색 API MSW 본인 검색 안되게 수정
  src/mocks/services/projectServiceHandler.ts
  src/mocks/services/teamServiceHandler.ts
  src/mocks/services/userServiceHandler.ts
Labels: 💉 Fix

#296 Config: #295 CryptoJS Secret Key 환경 변수 추가
  .github/workflows/deploy.yaml
Labels: ⚙️ Config

#281 Fix: #278 팀 관리 페이지 프로젝트 삭제 오류 수정 및 UI 개선
  src/hooks/query/useTeamQuery.ts
  src/layouts/page/SettingLayout.tsx
  src/layouts/page/TeamSettingLayout.tsx
  src/mocks/services/teamServiceHandler.ts
  src/pages/setting/TeamInvitedPage.tsx
  src/pages/setting/TeamJoinedPage.tsx
Labels: 💉 Fix, 🎨 UI

#300 Fix: #299 이미지 업로드 및 조회 오류 수정
  src/components/user/auth-form/ProfileImageContainer.tsx
  src/hooks/query/useUserQuery.ts
  src/mocks/services/authServiceHandler.ts
  src/mocks/services/userServiceHandler.ts
  src/pages/user/SignInPage.tsx
Labels: 🐞 Bug, 💉 Fix

#298 Fix: #297 팀 목록 페이지 UI 깨짐 수정
  src/components/project/ProjectItem.tsx
  src/layouts/page/TeamLayout.tsx
Labels: 💉 Fix

#304 Fix: #303 로그인 요청에 withCredentials 설정 추가
  src/services/authService.ts
Labels: 💉 Fix

#306 Fix: #305 프로젝트원 추가 API URI 수정
  src/services/projectService.ts
Labels: 💉 Fix

#309 Feat: #308 프로젝트 상세 페이지 프로젝트 설정 수정 모달 추가
  src/layouts/page/ProjectLayout.tsx
Labels: 🌟 Feature

#312 Refactor: #310 MSW 처리중teamService 기능 리팩토링
  .eslintrc.cjs
  src/mocks/mockAPI.ts
  src/mocks/mockUtils.ts
  src/mocks/services/projectServiceHandler.ts
  src/mocks/services/taskServiceHandler.ts
  src/mocks/services/teamServiceHandler.ts
  src/types/RoleType.tsx
  src/types/TeamType.tsx
Labels: 💉 Fix, 🛠️ Refactor

#311 Fix: #302 유저 검색기능 오류 수정
  src/mocks/services/projectServiceHandler.ts
Labels: 💉 Fix

#307 Fix: #301 프로젝트 생성 & 할 일 생성 날짜 종료일 수정
  src/components/common/PeriodDateInput.tsx
  src/components/modal/project/ModalProjectForm.tsx
  src/components/modal/project/UpdateModalProject.tsx
  src/components/modal/task/ModalTaskForm.tsx
  src/components/modal/task/UpdateModalTask.tsx
  src/constants/formValidationRules.ts
Labels: 💉 Fix

#314 Refactor: #310 MSW 처리중 userServiceHandler 기능 리팩토링
  src/mocks/mockAPI.ts
  src/mocks/mockData.ts
  src/mocks/mockHash.ts
  src/mocks/services/teamServiceHandler.ts
  src/mocks/services/userServiceHandler.ts
  src/types/MockType.tsx
Labels: 🛠️ Refactor

#316 Feat: #315 TeamCoworker, TeamCoworkerForm 타입 재정의
  src/mocks/services/teamServiceHandler.ts
  src/services/teamService.ts
  src/types/TeamType.tsx
Labels: 🌟 Feature
