Repository GU-99/grow-up-fe, pull requests merged in 2024-11, with the labels that each got.

#256 Feat: #253 프로젝트 팀원 삭제 추가
  src/components/modal/project/UpdateModalProject.tsx
  src/hooks/query/useProjectQuery.ts
  src/mocks/mockAPI.ts
  src/mocks/services/projectServiceHandler.ts
  src/services/projectService.ts
Labels: 🌟 Feature

#259 Config: #258 스테이징 환경에 https 설정 적용
  .gitignore
  package.json
Labels: ⚙️ Config

#260 Formatting: #257 권한 설명 변경
  src/components/common/RoleTooltip.tsx
  src/constants/role.ts
Labels: ✨ Formatting

#263 Fix: #233 새로고침 시 zustand 스토어 초기화되는 문제 수정
  src/components/common/Header.tsx
  src/components/user/auth-form/ProfileImageContainer.tsx
  src/mocks/services/authServiceHandler.ts
  src/routes/AfterLoginRoute.tsx
  src/routes/BeforeLoginRoute.tsx
  src/stores/useStore.ts
Labels: 🐞 Bug, 💉 Fix

#264 Feat: #261 유저 전체 검색 mswHandler 추가 & 팀 생성 시 HEAD 권한 삭제
  src/components/common/UserRoleSelectBox.tsx
  src/components/modal/team/ModalTeamForm.tsx
  src/constants/role.ts
  src/mocks/services/userServiceHandler.ts
Labels: 🌟 Feature

#271 Config: #269 Github Actions를 통해 테스트 통과 여부 검사 설정
  .github/workflows/vitest.yaml
  package.json
Labels: ⚙️ Config

#267 Fix: #266 AT 기간 만료 시 로직 수정
  src/stores/useStore.ts
Labels: 🐞 Bug, 💉 Fix

#273 Feat: #197 메타 데이터를 설정하는 컴포넌트 추가 및 적용
  index.html
  package.json
  public/.gitkeep
  public/favicon.ico
  src/assets/og_logo.png
  src/components/common/Meta.tsx
  src/main.tsx
  src/mocks/services/authServiceHandler.ts
  src/mocks/services/projectServiceHandler.ts
  src/mocks/services/statusServiceHandler.ts
  src/mocks/services/taskServiceHandler.ts
  src/mocks/services/teamServiceHandler.ts
  src/mocks/services/userServiceHandler.ts
  src/pages/NotFoundPage.tsx
  src/pages/project/CalendarPage.tsx
  src/pages/project/KanbanPage.tsx
  src/pages/setting/TeamInvitedPage.tsx
  src/pages/setting/TeamJoinedPage.tsx
  src/pages/setting/UserAuthenticatePage.tsx
  src/pages/setting/UserPasswordSettingPage.tsx
  src/pages/setting/UserSettingPage.tsx
  src/pages/team/TeamPage.tsx
  src/pages/user/SearchIdPage.tsx
  src/pages/user/SearchPasswordPage.tsx
  src/pages/user/SignInPage.tsx
  src/pages/user/SignUpPage.tsx
  src/services/axiosProvider.ts
  yarn.lock
Labels: 🌟 Feature

#277 Fix: #274 팀 가입 현황과 대기 현황 필터링이 반대로 설정된 문제 해결
  src/hooks/query/useTeamQuery.ts
  src/mocks/mockData.ts
  src/mocks/services/teamServiceHandler.ts
Labels: 💉 Fix

#276 Fix: #275 로그아웃시 Access Token이 포함되도록 수정
  src/mocks/services/authServiceHandler.ts
  src/services/authService.ts
Labels: 💉 Fix
